function displayChekList(response){
    new Typewriter("#travel-cheklist",{
        strings:response.data.answer,
        autoStart:true,
        delay:1,
        cursor:"",
    });

}
function displayList(event){
    event.preventDefault();


let instructionsInput=document.querySelector("#user-instructions");

 let context=`You are well traveld expert.When asked, what is the 10 clothes items and 5 essentsial that you need to pack, when traveling to  user instructions destination.Make sure to use user instructions.Make the sentence short. Separate each answer   with <br /><br />.  And use chekcbox before every item , but DO NOT check the box. On the final line below the suggestions, sign the result with 'Generated by SheCodes AI' inside <small> and <em> elements. Include a <br /> before the sign. Do NOT put this sign at the top.";`;
 let prompt=`Generate 10  clothes  items and 5 travel essentsial  for traveling for the first time to ${instructionsInput.value}`;
 let apiKey="fd0f7619afd34b6f4ebdft43802e1ofb";
 let apiUrl=`https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;
axios.get(apiUrl).then(displayChekList);

let travelElement=document.querySelector("#travel-cheklist");
travelElement.classList.remove("hidden");
travelElement.innerHTML=`<div class="generating">💡 Generating travel ChekList about ${instructionsInput.value}`;
}

let travelFormElement=document.querySelector("#travel-form");
travelFormElement.addEventListener("submit",displayList);